### ISSUE TITLE
Check for domain availability only in ISPConfig

### ISSUE THREAD

**Issue by ole1986** [ole1986/wp-ispconfig3#24]
Currently wp-ispconfig3 uses `whois` to check for avaialble domains It was requested to only check the domain against ISPConfig (through REST API).

Therefore I will provide a new option soon

Pingback: https://github.com/ole1986/wc-invoice-pdf/issues/5

**Comment by ole1986** [comment]
Unfortunately there is no proper way to do a REST API call and request all domain being used by the websites/clients.

Only option is to receive all available sites, based on the given sys_userid and sys_usergroup

See: https://git.ispconfig.org/ispconfig/ispconfig3/blob/master/interface/lib/classes/remote.d/sites.inc.php#L831

**Comment by MachineITSvcs** [comment]
Is there a way to loop through all users by ID and get each user's group's?
And run that function against the returned values? If so, I'm sure it can
all be done in the same SOAP connection before close.

--
Collin Machine
- Machine IT Services Founder and CEO

**Comment by ole1986** [comment]
I am currently working on it... Almost done but being also busy with other stuff unfortunately

**Comment by ole1986** [comment]
BONUS:

Once then wp-ispconfig3 plugin is enabled you can access the domain check using ajax request (E.g. jQuery)

```
var domain = 'yourdomain.net';
$.post(ajaxurl, { action: 'ispconfig_whois', 'domain': domain }, null, 'json').done(function(resp){
    if (resp.class !== 'ispconfig-msg-error') {
        // is free
    } else {
        // is reserved
    }
});
```

**Comment by MachineITSvcs** [comment]
Nice! That'll help a lot for field validation before form submission!

--
Collin Machine
- Machine IT Services Founder and CEO

**Comment by tkembo** [comment]
Thanks for the taking care of this. It think the whois validation should be removed too because firstly it prevents you from proceeding with a domain that has already been registered. For example, I could have a domain that is registered and being hosted on a different host and I want to move it to an an ISPConfig instance.
Secondly, it prevents you from using a domain that is currently not supported by this particular whois service - I tested it for for example .co.zw domains and I get a "The domain name is invalid" error. I think the only check should be if the domain is already in ISPConfig the ISPConfig instance.
