### ISSUE TITLE
The domain is already registered

### ISSUE THREAD

**Issue by Simon-CR** [ole1986/wp-ispconfig3#29]
any domain that I put in the field returns that the domain is already registered.

seems like there was another post over 2 years ago similar to this, but there was no real solution.

please advise

**Comment by ole1986** [comment]
@realbuz since version 1.4.3 you can switch between whois and your local ISPConfig database to verify if the domain is already registered.

This setting can be found in `WP-ISPConfig3` -> `Settings` -> `Domain Check` from the backend

![image](https://user-images.githubusercontent.com/4850116/68784640-2a429600-063d-11ea-9d16-6173bcc8a04e.png)

Also you can use the below `Regular expression` setting to customize your domain validation

**Comment by Simon-CR** [comment]
the checkbox is already enabled.  and if I try to uncheck and save it comes back checked again.

thanks

Simon

**Comment by Simon-CR** [comment]
running 1.4.4

**Comment by ole1986** [comment]
Pretty sure this is fixed in version 1.5.0 which I have not finalized yet for WordPress..

I might come up with a hotfix for version 1.4.5 and quickly release it under the WordPress plugins

**Comment by Simon-CR** [comment]
ok, that would be appreciated.

**Comment by Simon-CR** [comment]
ok so the checkbox now does what it should do and let me save.  However what needs to work is proper domain availability validation.  Can we troubleshoot why (when the box is checked) domain validation isn't working as it should ?

thanks

**Comment by ole1986** [comment]
When the Global domain check is **hooked** it verifies the domain availability by using the command `whois` 

Some TLD providers do not support this command, instead they pass you through their online service.

As an example:

````sh
whois test.es
 ````

Returns:
`This TLD has no whois server, but you can access the whois database at https://www.nic.es/`

While

```sh
whois somefreedomain.de
```

Returns:

````
Domain: test12313132123123.de
Status: free
````

The script can validate if a domain is available only for the second example.
There might be some other service (instead of whois) which is more accurate but may charge money for it.

**Comment by ole1986** [comment]
An alternate command would be:

```
dig +noall +answer <domain> NS
```

This should either return the related name servers (possible unavailable) or nothing.
Most linux systems do not have "dig" installed by default (`apt-get install dnsutils` for debian)

That is why I decided to use `whois`. But we can arrange another option to allow using `dig` instead if this is more reliable

**Comment by Simon-CR** [comment]
I dont mind having to install dig on the host in order to make the domain lookup more "accurate".

**Comment by ole1986** [comment]
Allow me to put this as a new issue. So we can primarily focus on it.
