### ISSUE TITLE
'Enable password syncronization' does not appear to be working

### ISSUE THREAD

**Issue by tawandakembo** [ole1986/wp-ispconfig3#31]
When the 'Enable password syncronization' setting is enabled and an account is created on the Wordpress site, the password to the wordpress site that is emailed to the customer is different from the password to the ISPConfig site. 
Secondly, I noticed that only the username/password to the wordpress is emailed to the customer. Is this a bug or is that expectation that the username/password to the ISPConfig site sends it's own credentials separately. Or should the username/password work for both sites?

**Comment by ole1986** [comment]
The password will be updated with ISPconfig3 whenever the admin or user is updating the password in wordpress.

Lets assume you have created a Gutenberg block using a "Create Client" action with **Client ID** set to **Generated** or **Default**.
Once you submit on the frontend, the plugin either generates a username or uses the given one to create a user on wordpress as well as on the ISPConfig3 side with the exact same password

When now **a user changes the password from wordpress it will automatically be updated to ISPConfig3**. Unfortunately it cannot do the other way around due to REST API limitation.

---

This should actually answer your second question. So, at the moment of submission the password is generated by the plugin and should be available as variable `[client_password]` for the confirmation email template.

**Comment by tawandakembo** [comment]
Thank you. This is very helpful
